-- CreateEnum
CREATE TYPE "IS_MESSAGE_HELPFUL" AS ENUM ('DEFAULT', 'HELPFUL', 'NOT_HELPFUL');

-- AlterTable
ALTER TABLE "Fragment" ADD COLUMN     "isHelpful" "IS_MESSAGE_HELPFUL" NOT NULL DEFAULT 'DEFAULT';
